# Generated by Django 3.2.12 on 2024-04-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_registration', 'User Registration'), ('user_login', 'User Login'), ('content_creation', 'Content Creation'), ('content_update', 'Content Update'), ('media_upload', 'Media Upload')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
