

# version: '3.8'

# services:
#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASS}

#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#       - /var/run/docker.sock:/var/run/docker.sock
#     ports:
#       - "8000:8000"
#     environment:
#       - DB_NAME=${DB_NAME}
#       - DB_USER=${DB_USER}
#       - DB_PASS=${DB_PASS}
#       - DB_SERVICE=db
#       - DB_PORT=${DB_PORT}
#     depends_on:
#       - db

# volumes:
#   postgres_data:


version: '3.8'
services:
  db:
    image: postgres:13
    container_name: db  # Ensure the container name matches the service name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db  # Ensure this matches the service name in Django settings
      - DB_PORT=5432  # PostgreSQL default port
    depends_on:
      - db

volumes:
  postgres_data:
