global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'laravel'
    metrics_path: '/metrics'  
      - targets: ['app:9000']
  
  - job_name: 'content_service'
    static_configs:
      - targets: ['content_service_web_1:9000']

  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service:3001']  

  - job_name: 'medea-service'
    static_configs:
      - targets: ['medea-service:3002']  
    
