---
# Content-Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      initContainers:
      - name: migrate
        image: content-service-1:latest
        imagePullPolicy: IfNotPresent
        command: ['bin/rails', 'db:migrate']
      containers:
      - name: content-service
        image: content-service-1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001

---
# Content-Service Service
apiVersion: v1
kind: Service
metadata:
  name: content-service-service
spec:
  type: NodePort
  selector:
    app: content-service
  ports:
    - protocol: TCP
      port: 3001
      nodePort: 30006

---
# User-Management Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: user-management:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000

---
# User-Management Service
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: NodePort
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 9000
      nodePort: 30009

---
# Medea-Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medea-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medea-service
  template:
    metadata:
      labels:
        app: medea-service
    spec:
      containers:
      - name: medea-service
        image: medea-service-1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3006

---
# Medea-Service Service
apiVersion: v1
kind: Service
metadata:
  name: medea-service-service
spec:
  type: NodePort
  selector:
    app: medea-service
  ports:
    - protocol: TCP
      port: 3006
      nodePort: 30007

---
# Prometheus Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9091

---
# Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9091
      nodePort: 30090

---
# Grafana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3010

---
# Grafana Service
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3010
      nodePort: 30030
