# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: user-management
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: user-management
#   template:
#     metadata:
#       labels:
#         app: user-management
#     spec:
#       containers:
#       - name: user-management
#         image: user-management:latest
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 9000 # Adjusted to match the application's actual port

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: user-management-service
# spec:
#   type: NodePort
#   selector:
#     app: user-management
#   ports:
#     - protocol: TCP
#       port: 9000 # Adjusted to match the container's port
#       targetPort: 9000 # Ensure this matches the containerPort if necessary
#       nodePort: 30005


apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: user-management:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: NodePort
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30005
